name: testmaker_student
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.5
  flutter_lints: ^2.0.2
  #  excel: ^2.0.4
  csv: ^5.0.2
  path: ^1.8.3
  get: ^4.6.5
  #  dartz: ^0.10.1
  http: ^0.13.6
  file_picker: ^5.3.2
  path_provider: ^2.0.15
  filesystem_picker: ^3.1.0
  device_apps: ^2.2.0
  url_launcher: ^6.1.11
  share_plus: ^7.0.2
  easy_localization: ^3.0.2
  device_preview: ^1.1.0  #^0.7.5
  flutter_launcher_icons: ^0.13.1
  sensors: ^2.0.3
  animated_theme_switcher: ^2.0.8
  shared_preferences: ^2.2.0
  dartz: ^0.10.1
  image_picker: ^0.8.9
  photo_view: ^0.14.0
  cached_network_image: ^3.2.3
  qr_bar_code_scanner_dialog: ^0.0.5
  image_cropper: ^4.0.0
  flutter_math_fork: ^0.7.1
  math_keyboard: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/translations/ar-DZ.json
    - assets/translations/en-US.json
    - assets/images/
    - assets/files/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 700
